include(FindPkgMacros)
findpkg_begin(CEGUI)

# Get path, convert backslashes as ${ENV_${var}}
getenv_path(CEGUI_HOME)

# construct search paths
set(CEGUI_PREFIX_PATH ${CEGUI_HOME} ${ENV_CEGUI_HOME})
create_search_paths(CEGUI)
# redo search if prefix path changed
clear_if_changed(CEGUI_PREFIX_PATH
  CEGUI_LIBRARY_FWK
  CEGUI_LIBRARY_REL
  CEGUI_LIBRARY_DBG
  CEGUI_INCLUDE_DIR
)

set(CEGUI_LIBRARY_NAMES CEGUIBase)
set(CEGUI_LIBRARY_NAMES2 CEGUIOgreRenderer)
get_debug_names(CEGUI_LIBRARY_NAMES)
get_debug_names(CEGUI_LIBRARY_NAMES2)

use_pkgconfig(CEGUI_PKGC CEGUI)

findpkg_framework(CEGUI)

find_path(CEGUI_INCLUDE_DIR NAMES CEGUI.h HINTS ${CEGUI_PREFIX_PATH}/cegui/include ${CEGUI_INC_SEARCH_PATH} ${CEGUI_PKGC_INCLUDE_DIRS} PATH_SUFFIXES CEGUI)

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(CEGUI_LIBRARY_DBG "")

  find_library(CEGUI_LIBRARY_DBG1 NAMES ${CEGUI_LIBRARY_NAMES_DBG} HINTS ${CEGUI_PREFIX_PATH}/cegui/lib ${CEGUI_LIB_SEARCH_PATH} ${CEGUI_PKGC_LIBRARY_DIRS} PATH_SUFFIXES "" debug)
  set(CEGUI_LIBRARY_DBG ${CEGUI_LIBRARY_DBG} ${CEGUI_LIBRARY_DBG1})
  find_library(CEGUI_LIBRARY_DBG2 NAMES ${CEGUI_LIBRARY_NAMES2_DBG} HINTS ${CEGUI_PREFIX_PATH}/cegui/lib ${CEGUI_LIB_SEARCH_PATH} ${CEGUI_PKGC_LIBRARY_DIRS} PATH_SUFFIXES "" debug)
  set(CEGUI_LIBRARY_DBG ${CEGUI_LIBRARY_DBG} ${CEGUI_LIBRARY_DBG2})
else()
  set(CEGUI_LIBRARY_REL "")

  find_library(CEGUI_LIBRARY_REL1 NAMES ${CEGUI_LIBRARY_NAMES} HINTS ${CEGUI_PREFIX_PATH}/cegui/lib ${CEGUI_LIB_SEARCH_PATH} ${CEGUI_PKGC_LIBRARY_DIRS} PATH_SUFFIXES "" release relwithdebinfo minsizerel)
  set(CEGUI_LIBRARY_REL ${CEGUI_LIBRARY_REL} ${CEGUI_LIBRARY_REL1})
  find_library(CEGUI_LIBRARY_REL2 NAMES ${CEGUI_LIBRARY_NAMES2} HINTS ${CEGUI_PREFIX_PATH}/cegui/lib ${CEGUI_LIB_SEARCH_PATH} ${CEGUI_PKGC_LIBRARY_DIRS} PATH_SUFFIXES "" release relwithdebinfo minsizerel)
  set(CEGUI_LIBRARY_REL ${CEGUI_LIBRARY_REL} ${CEGUI_LIBRARY_REL2})
endif()

make_library_set(CEGUI_LIBRARY)

if (WIN32)
  set(CEGUI_BIN_SEARCH_PATH ${CEGUI_HOME}/bin ${ENV_CEGUI_HOME}/bin)

  find_file(CEGUI_BINARY_REL NAMES "CEGUIBase.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" release relwithdebinfo minsizerel)
  set(CEGUI_BINARIES_REL ${CEGUI_BINARIES_REL} ${CEGUI_BINARY_REL})
#  find_file(CEGUI_BINARY_REL2 NAMES "CEGUIOgreRenderer.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
#    PATH_SUFFIXES "" release relwithdebinfo minsizerel)
#  set(CEGUI_BINARIES_REL ${CEGUI_BINARIES_REL} ${CEGUI_BINARY_REL2})
  find_file(CEGUI_BINARY_REL3 NAMES "CEGUIExpatParser.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" release relwithdebinfo minsizerel)
  set(CEGUI_BINARIES_REL ${CEGUI_BINARIES_REL} ${CEGUI_BINARY_REL3})
  find_file(CEGUI_BINARY_REL4 NAMES "CEGUIFalagardWRBase.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" release relwithdebinfo minsizerel)
  set(CEGUI_BINARIES_REL ${CEGUI_BINARIES_REL} ${CEGUI_BINARY_REL4})

  find_file(CEGUI_BINARY_DBG NAMES "CEGUIBase_d.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" debug )
  set(CEGUI_BINARIES_DBG ${CEGUI_BINARIES_DBG} ${CEGUI_BINARY_DBG})
  find_file(CEGUI_BINARY_DBG2 NAMES "CEGUIOgreRenderer_d.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" debug )
  set(CEGUI_BINARIES_DBG ${CEGUI_BINARIES_DBG} ${CEGUI_BINARY_DBG2})
  find_file(CEGUI_BINARY_DBG3 NAMES "CEGUIExpatParser_d.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" debug )
  set(CEGUI_BINARIES_DBG ${CEGUI_BINARIES_DBG} ${CEGUI_BINARY_DBG3})
  find_file(CEGUI_BINARY_DBG4 "CEGUIFalagardWRBase_d.dll" HINTS ${CEGUI_BIN_SEARCH_PATH}
    PATH_SUFFIXES "" debug )
  set(CEGUI_BINARIES_DBG ${CEGUI_BINARIES_DBG} ${CEGUI_BINARY_DBG4})
endif()
mark_as_advanced(CEGUI_BINARY_REL CEGUI_BINARY_DBG)


findpkg_finish(CEGUI)

# add parent of CEGUI folder to support CEGUI/CEGUI.h

get_filename_component(CEGUI_INCLUDE_PARENT_DIR ${CEGUI_INCLUDE_DIR} PATH)
set (CEGUI_INCLUDE_DIRS ${CEGUI_INCLUDE_PARENT_DIR})


# Reset framework finding
set(CMAKE_FIND_FRAMEWORK "FIRST")
